//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_category()
        {
            this.product_category = new HashSet<product_category>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> FatherId { get; set; }
        public Nullable<int> CategoryLevel { get; set; }
        public int OrderNumber { get; set; }
        public bool Active { get; set; }
        public string PathUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_category> product_category { get; set; }
    }
}
