//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class p_provider
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public p_provider()
        {
            this.product = new HashSet<product>();
            this.product1 = new HashSet<product>();
            this.product2 = new HashSet<product>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string TelPhone { get; set; }
        public string Phone { get; set; }
        public string Phone2 { get; set; }
        public string Town { get; set; }
        public string StreetName { get; set; }
        public Nullable<int> StreetNumber { get; set; }
        public Nullable<int> HouseNumber { get; set; }
        public string Zip { get; set; }
        public string AddressComment { get; set; }
        public string ComaxId { get; set; }
        public string Email { get; set; }
        public string Tz { get; set; }
        public string Gender { get; set; }
        public System.DateTime InsertDate { get; set; }
        public string Comment { get; set; }
        public Nullable<int> DeliveryFrequencyId { get; set; }
        public Nullable<bool> CompleteCarton { get; set; }
        public Nullable<int> SafetyStock { get; set; }
        public Nullable<int> PartSafetyStock { get; set; }
        public Nullable<int> OrderThroughId { get; set; }
        public Nullable<int> internalId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product> product2 { get; set; }
    }
}
