//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.family1 = new HashSet<family>();
            this.product_category = new HashSet<product_category>();
        }
    
        public int Mkt { get; set; }
        public string SubMkt { get; set; }
        public string Barcode { get; set; }
        public string ProductName { get; set; }
        public int StorageModeId { get; set; } = 1;
        public string Description { get; set; }
        public int BrandId { get; set; } = 1;
        public bool ViewBrand { get; set; } = true;
        public Nullable<int> PackageQuantity { get; set; }
        public Nullable<double> WeightQuantity { get; set; }
        public int UnitMeasureId { get; set; } = 1;
        public bool Weighable { get; set; }
        public Nullable<double> WeightUnit { get; set; }
        public Nullable<int> FamilyId { get; set; } = 1;
        public int ViewOutOfStockId { get; set; } = 1;
        public int KashrutFeatureId { get; set; } = 1;
        public int KashrutId { get; set; } = 1;
        public Nullable<int> PassoverKashrutId { get; set; } = 1;
        public Nullable<int> PassoverFeatureId { get; set; } = 1;
        public Nullable<int> AfterPassoverId { get; set; } = 1;
        public bool VerifyKashrut { get; set; } = true;
        public Nullable<int> DairyId { get; set; } = 1;
        public Nullable<bool> DepositProduct { get; set; }
        public Nullable<bool> VatProduct { get; set; }
        public Nullable<bool> SupervisedPrice { get; set; }
        public Nullable<double> BuyingPrice { get; set; }
        public Nullable<double> PricePerProfitPercent { get; set; }
        public Nullable<double> Package_PricePerUnit { get; set; }
        public Nullable<int> ManufacturerId { get; set; } = 1;
        public Nullable<int> ProviderId { get; set; } = 1;
        public Nullable<int> ExchangeProviderId { get; set; } = 1;
        public Nullable<int> ExchangeProvider2Id { get; set; } = 1;
        public Nullable<double> GrossWeightLoss { get; set; }
        public Nullable<int> ManufacturerPackageQuantity { get; set; }
        public Nullable<int> MiniPackageQuantity { get; set; }
        public Nullable<int> MasterPackageQuantity { get; set; }
        public Nullable<int> FlatQuantity { get; set; }
        public Nullable<double> ManufacturerPackageWeight { get; set; }
        public Nullable<int> ManufacturerPackageSize { get; set; }
        public Nullable<int> UnloadManufacturerPackageId { get; set; } = 1;
        public Nullable<int> BoxQuantity { get; set; }
        public Nullable<int> BoxTypeId { get; set; } = 1;
        public Nullable<int> BoxStorageWayId { get; set; } = 1;
        public Nullable<double> Height { get; set; }
        public Nullable<int> Cube { get; set; }
        public Nullable<int> Action { get; set; }
        public Nullable<int> ExpiredDays { get; set; }
        public Nullable<int> MinExpiredDays { get; set; }
        public Nullable<bool> ExpiredAllert { get; set; }
        public Nullable<bool> Separated { get; set; }
        public System.DateTime InsertDate { get; set; }
        public Nullable<System.DateTime> UpdateDateTime { get; set; }
        public bool FamilyProduct { get; set; }
        public bool CollectedProduct { get; set; } = true;
        public Nullable<int> UserId { get; set; }
        public Nullable<bool> DailyUpdate { get; set; }
        public double orderNumber { get; set; }
        public double WeightJump { get; set; }
        public double GrossWeight { get; set; }
        public bool NewInGs1 { get; set; }
        public Nullable<int> ProductGs1Id { get; set; }
        public Nullable<bool> ShowExpired { get; set; } = true;
        public Nullable<int> NewStatus { get; set; } = 0;
    
        public virtual family family { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<family> family1 { get; set; }
        public virtual p_brand p_brand { get; set; }
        public virtual p_provider p_provider { get; set; }
        public virtual p_provider p_provider1 { get; set; }
        public virtual p_provider p_provider2 { get; set; }
        public virtual p_unit_measure p_unit_measure { get; set; }
        public virtual p_unit_measure p_unit_measure1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<product_category> product_category { get; set; }
    }
}
