//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_category
    {
        public int Id { get; set; }
        public int ProductMkt { get; set; }
        public int CategoryId { get; set; }
        public System.DateTime InsertDate { get; set; }
    
        public virtual p_category p_category { get; set; }
        public virtual product product { get; set; }
    }
}
