//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_view
    {
        public int Mkt { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> PackageQuantity { get; set; }
        public Nullable<int> ProviderId { get; set; }
        public string ProviderName { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> ManufacturerPackageQuantity { get; set; }
    }
}
